### ISSUE TITLE
Exceeding NotebookApp.iopub_data_rate_limit

### ISSUE THREAD

**Issue by gyuhyeokcho** [rs-station/careless#135]
Hi, @kmdalton, 

I've been working on scaling and merging multiple crystal diffraction data in Google Colab. However, I've encountered a particular issue.
Here's the command I used:
>!mkdir -p 1_DOF32
!careless mono \
    --studentt-likelihood-dof=32 \
    --disable-image-scales \
    --merge-half-datasets \
    --iterations=30_000 \
    --test-fraction 0.05 \
    --wilson-prior-b 80 \
    --dmin 2.100 \
    "BATCH,dHKL,Hobs,Kobs,Lobs,XCAL,YCAL,ZCAL,RLP,PEAK,CORR,MAXC,XOBS,YOBS,ZOBS,ALF0,BET0,ALF1,BET1,PSI,ISEG" \
    INTEGRATE_2298defa_hkl2mtz.mtz \
    INTEGRATE_2299beam_hkl2mtz.mtz \
    INTEGRATE_2302save1_hkl2mtz.mtz \
    INTEGRATE_2303defa_hkl2mtz.mtz \
    1_DOF32/DOF32

I received the following output:
>Careless version 0.3.9
Metadata column "ISEG" with zero standard deviation will not be standardized.
/usr/local/lib/python3.10/site-packages/careless/io/formatter.py:29: UserWarning: Metadata column "ISEG" with zero standard deviation will not be standardized.
  warnings.warn(message)
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

>Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

I tried increasing the `NotebookApp.iopub_data_rate_limit`, but it seems that this value is fixed in Google Colab and cannot be easily changed. I've noticed that others who faced similar messages from Colab bypassed the issue by removing the print statement. Would it be possible to disable the print statement in Careless to resolve this issue?

**Comment by kmdalton** [comment]
Most of what `careless` prints to screen is just the progress bar which uses [tqdm](https://github.com/tqdm/tqdm). `tqdm` actually sends a new line of text to the terminal every time the progress bar is updated. I'm guessing this is what colab is complaining about. You can disable the bar with the `--disable-progress-bar` flag. 

Unrelated note: 
If the value of "ISEG" is the same for all your reflections, I would recommend removing it from your metadata kwargs.

**Comment by kmdalton** [comment]
Hi @gyuhyeokcho,

Can you tell me what the cell and spacegroup are for your inputs? You can get this from `rs.mtzdump *.mtz`. I think your issue is that your inputs are not isomorphous, and careless doesn't formally support that right now (see: https://github.com/rs-station/careless/issues/35). You can workaround the issue by setting the cell and spacegroup to be the same for all the inputs. This is straightforward to do with reciprocalspaceship. Let me know if you need help!

I think this is an area where careless needs to be improved. I would love feedback from users about what you would actually like to see happen in this scenario? As I see it the options are:
 -   Refuse to merge non-isomorphous cells and provide a helpful error message
 -  Use the first cell in the list to determine the ASU for merging
 -  Use the average cell to determine the ASU for merging
Perhaps for the final two options, it'd be a good idea to print a warning as well. Let me know what you think. This is a very longstanding issue, and I love to fix it.

**Comment by DorisMai** [comment]
Just throwing another idea here — my current workaround is adding an argument ”—unitcell” to allow me to supply a set of parameters and ignore the ones from input mtz files.

> I think this is an area where careless needs to be improved. I would love feedback from users about what you would actually like to see happen in this scenario? As I see it the options are:
> 
> * Refuse to merge non-isomorphous cells and provide a helpful error message
> * Use the first cell in the list to determine the ASU for merging
> * Use the average cell to determine the ASU for merging
> 
> Perhaps for the final two options, it'd be a good idea to print a warning as well. Let me know what you think. This is a very longstanding issue, and I love to fix it.

**Comment by kmdalton** [comment]
@DorisMai, we do encourage pull requests around these parts :)

**Comment by kmdalton** [comment]
Related: #136

**Comment by gyuhyeokcho** [comment]
Thank you for your feedback! I've noticed that I used multiple datasets with different space groups for Careless. Here are the rs.mtzdump results for these datasets. I'd like to change the space group and unit cell parameters of the other datasets with the first one in each set. Can you advise on how to do this?

Datasets #1
Spacegroup: C2
Extended Hermann-Mauguin name: C 1 2 1
Unit cell dimensions: 166.247 95.476 198.074 90.000 90.394 90.000

Spacegroup: C2
Extended Hermann-Mauguin name: C 1 2 1
Unit cell dimensions: 166.158 95.321 198.066 90.000 90.420 90.000

Spacegroup: P1
Extended Hermann-Mauguin name: P 1
Unit cell dimensions: 96.022 96.358 199.240 89.300 89.946 60.186

Spacegroup: C2
Extended Hermann-Mauguin name: C 1 2 1
Unit cell dimensions: 167.024 95.944 199.729 90.000 90.779 90.000

Datasets #2
Spacegroup: P1
Extended Hermann-Mauguin name: P 1
Unit cell dimensions: 94.120 94.060 194.799 87.683 88.221 60.081

Spacegroup: P1
Extended Hermann-Mauguin name: P 1
Unit cell dimensions: 94.019 94.120 195.117 87.754 88.328 60.158

**Comment by kmdalton** [comment]
Hi @gyuhyeokcho, this is pretty easy to do in python with reciprocalspaceship depending on your level of programming experience. Here is a simple script which should do what you want: 

```python
import reciprocalspaceship as rs

reference_mtz = 'dataset_1.mtz'

mtzs = [
    'dataset_2.mtz',
    'dataset_3.mtz',
    'dataset_4.mtz',
]

ds = rs.read_mtz(reference_mtz)
cell = ds.cell
spacegroup = ds.spacegroup

for mtz in mtzs:
    ds = rs.read_mtz(mtz)
    ds.cell = cell
    ds.spacegroup = spacegroup
    output_mtz = mtz[:-4] + "_updated.mtz"
    ds.write_mtz(output_mtz)
```


I will caution you that in some cases, reindexing operations need to applied to the Miller indices in addition to just changing the cell. This is important if you are either changing the space group or have a space group where there are multiple indexing solutions (indexing ambiguity). Neither of these space groups have indexing ambiguities. However, you won't be able to merge a P1 indexed data set with a C2 without doing some more work. I hesitate to offer more guidance without knowing more about your specific use case. 

I hope this makes sense. Please let me know if this solution works for you.

**Comment by gyuhyeokcho** [comment]
It worked for me. Thank you for your help!
