### ISSUE TITLE
--mlp-width should have a sensible default

### ISSUE THREAD

**Issue by kmdalton** [rs-station/careless#142]
Automatically setting mlp-width leads to excessive memory when combined with positional encoding. It also makes crossvalidation between different metadata scenarios invalid. I should just change the default `--mlp-width` to be a sensible value like 10.

**Comment by kmdalton** [comment]
resolved by #144

**Comment by DHekstra** [comment]
At the risk of overextrapolating from two examples (lysozyme and DHFR laue anomalous), perhaps the default `--mlp-width` should be larger, at least until we revisit this?
