### ISSUE TITLE
warning about r>1 or r<0?

### ISSUE THREAD

**Issue by DHekstra** [rs-station/careless#147]
motivated by some intrepid users:
double-wilson parameters < 0 or >1 are not intended use cases and may lead to unexpected behavior. 
Perhaps the default should be to resort to univariate priors for negative r and throw an error for r>1?

**Comment by kmdalton** [comment]
Without thinking too hard, I feel negative values should be a warning. I can't say for sure there is no legitimate use case for negative correlation coefficients. Greater than one being an error makes sense to me.

**Comment by kmdalton** [comment]
resolved by #170
