### ISSUE TITLE
spearman CCpreds "look much different" from weighted pearson CCpreds  

### ISSUE THREAD

**Issue by hkwang** [rs-station/careless#153]
With `careless==0.4.1`, I compared the `careless.ccpred` of two datasets with both` -m spearman` and `-m pearson`. These two datasts are Vukica's PYP dataset, processed with precognition for the careless paper (according to Doeke), and an e35_PDZ dataset processed with laue-dials.

CCpreds for PYP, weighted Pearson: 
![image](https://github.com/rs-station/careless/assets/98353449/79922ea9-a4cc-4580-82b9-61468e9f1696)

CCpreds for PYP, Spearman: 
![image](https://github.com/rs-station/careless/assets/98353449/5b6043c3-c1ed-45cd-85dc-976d506070ee)

CCpreds for e35_PDZ, weighted Pearson: 
![image](https://github.com/rs-station/careless/assets/98353449/55af2781-a821-428e-874c-ae62a87e9544)
CCpreds for e35_PDZ, Spearman: 
![image](https://github.com/rs-station/careless/assets/98353449/7fb06de5-6bf2-49f2-bddc-86eee1e23a2f)

For each dataset, the CCpreds look "much different" between the two datasets.

**Comment by kmdalton** [comment]
@hkwang,  is this at all unexpected? they're different estimators. do you think there is a bug?

**Comment by kmdalton** [comment]
I'm going to close this issue, because I don't see how it is a bug. Feel free to re-open if I missed something.
