### ISSUE TITLE
Support reindexing operators in the double wilson prior

### ISSUE THREAD

**Issue by kmdalton** [rs-station/careless#158]
Perturbations sometimes change the space group in comparative crystallography. For the double Wilson prior to flexibly account for this, it needs to support reindexing between children and parents. the `reindexing_ops` [branch](https://github.com/rs-station/careless/tree/reindexing_ops) implements this feature. it still needs to be tested and merged into main.

**Comment by kmdalton** [comment]
@DHekstra -- have you made any progress benchmarking this feature?

**Comment by DHekstra** [comment]
I think we can close this.
