### ISSUE TITLE
Support Non-Isomorphous Inputs

### ISSUE THREAD

**Issue by kmdalton** [rs-station/careless#35]
It may be impossible to supply multiple `mtz` files without `--separate-files` in the current experimental branch. I should check on this and write a test.

**Comment by JBGreisman** [comment]
Just to comment on this -- the default behavior in `rs` for `rs.concat()`, `DataSet.append()`, `DataSet.join()`, and `DataSet.merge()` is to use the first cell in the list (or for the `DataSet` ones, to keep the cell of the calling `DataSet`). Each of the methods also have a `check_isomorphous=True` argument, that can be set to False to avoid this check. 

Those methods and the `check_isomorphous` flag may provide a simple way to implement this sort of behavior.
