### ISSUE TITLE
Standardizing Columns with One Unique Value

### ISSUE THREAD

**Issue by kmdalton** [rs-station/careless#64]
Careless automatically standardizes the columns in input mtz files. In the case where there is only one unique value in a column, the estimated standard deviation will be 0 which leads to a divide by zero and the contents of that column will be nans. In this case, optimization immediately fails with a cryptic error message. The question is what is a better behavior? I can think of 3 possibilities:
1) Raise an error
2) Set all the values to zero
3) Leave the values unchanged

While (1) is a clean solution, it does not guarantee the ability to compare arbitrary subsets of data with the same merging protocol. (2) is also a clean solution, but it doesn't play nice with transfer learning because zero might have a different meaning between subsets of data. (3) gives the user the most flexibility, but it really requires the user to standardize their data beforehand. It may lead to nasty behavior for some use cases. 

On a related note, it might be sensible to add a flag to disable standardization. 

At the moment, the correct set of behaviors is not obvious to me. I'm going to think about this for a bit. I'd welcome any feedback on this issue from, for instance, @DHekstra.

**Comment by DHekstra** [comment]
I would suggest we take option 1, with an optional flag to enable 3.

**Comment by kmdalton** [comment]
This was solved in #83 by skipping standardization and warning users.
