### ISSUE TITLE
libdevice error with v 0.2.5 but not 0.2.4

### ISSUE THREAD

**Issue by DHekstra** [rs-station/careless#81]
Running Careless with the following arguments, 

`poly --separate-files --merge-half-datasets --half-dataset-repeats=1 --mlp-layers=10 --image-layers=1 --dmin=1.7 --iterations=30_000 --positional-encoding-frequencies=0 --positional-encoding-keys=X,Y --test-fraction=0.10 --seed=29725 --double-wilson-parents=None,0,0,1,2,1,2 --double-wilson-r=0.,0.99,0.99,0.99,0.99,0.99,0.99 --wavelength-key=Wavelength --refine-uncertainties --studentt-likelihood-dof=128 BATCH,Wavelength,dHKL,Hobs,Kobs,Lobs,X,Y,file_id (some mtz files)`

'I get a libdevice not found' error (see attached for full traceback. Is this some kind of CUDA version error?

[myoutput_38465658.err.txt](https://github.com/rs-station/careless/files/10369762/myoutput_38465658.err.txt)

**Comment by kmdalton** [comment]
I have encountered this recently as well. I'll try to look into it this week. There is a workaround for our cluster. I'll send the details via slack later.

**Comment by kmdalton** [comment]
turns out this issue is because tf 2.11 moved to using cuda 11.2 which is not available on our cluster. this is not really a bug with careless.  it is more an issue with our cluster.
