### ISSUE TITLE
Does not install GPU capabilities

### ISSUE THREAD

**Issue by james-vincent** [rs-station/careless#85]
Install on CentOS 7.9 machine with GeForce GTX 1080 Ti fails to install GPU capable tensorflow. 
Examples run on all CPU. 

Installed with python 3.9:
python -m pip install --upgrade pip
python -m pip install careless

No cuda toolkit, cudnn, no detection of GPU running examples. Is there an alternative install procedure?

**Comment by kmdalton** [comment]
Could you paste the output of `nvidia-smi`? Thanks.

**Comment by james-vincent** [comment]
$ nvidia-smi
Thu Jan 19 16:11:06 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:09:00.0 Off |                  N/A |
| 23%   37C    P0    76W / 250W |    100MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:88:00.0 Off |                  N/A |
| 23%   29C    P0    61W / 250W |      2MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     18716      G   /usr/bin/X                         74MiB |
|    0   N/A  N/A     37215      G   .../bin/Linux-x86_64/maestro       12MiB |
|    0   N/A  N/A     38869      G   .../bin/Linux-x86_64/maestro        9MiB |
+-----------------------------------------------------------------------------+

**Comment by kmdalton** [comment]
Nothing concerning there. What about `nvcc --version`?

**Comment by james-vincent** [comment]
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Jan_28_19:32:09_PST_2021
Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0

**Comment by kmdalton** [comment]
On some systems, it can be tricky to convince TF to use the GPU. Lately, I have had good luck using Miniconda to install the cuda toolkit and cudnn as described in the [tensorflow docs](https://www.tensorflow.org/install/pip#linux_1). I'd recommend following steps 1-5 to install tensorflow in a fresh conda environment prior to installing `careless`. 

Alternatively or additionally, we can get more info about your specific issue by running careless with the `--tf-debug` flag. This will print a lot of TF debugging info which is usually suppressed.

**Comment by kmdalton** [comment]
To answer your question directly, `pip` is the only supported route to install `careless`. The reason being is that it is the only way that non-containerized TensorFlow binaries are distributed. Rather than install the PyPI package, you may install careless from source via
```bash
pip install git+https://github.com/rs-station/careless
```
or
```bash
git clone https://github.com/rs-station/careless
cd careless
pip install -e .
```
However, I wouldn't expect that to help with any CUDA issues. You're most likely to have success by first installing TF by the miniconda route I mentioned. 

I will note that there are also [Docker images](https://www.tensorflow.org/install/docker) available for TensorFlow. Presumably, if you configure one of those you can just install careless on top of it via pip. However, I have never attempted that, and I'm afraid it would be better to ask the TensorFlow devs for help.

**Comment by james-vincent** [comment]
Is tensorRT required? Following the procedure above throws error:

Could not load dynamic library 'libnvinfer.so.7

**Comment by kmdalton** [comment]
TensorRT is not required.

**Comment by kmdalton** [comment]
@james-vincent, I added a section to the README to offer some guidance about this issue. Let me know if there is anything else I can do. When you're satisfied, let me know and I will close this issue.

**Comment by james-vincent** [comment]
We have success now. We found there is an issue with TF 2.11 and tensorrt:

https://github.com/tensorflow/tensorflow/issues/57671

We were able to install and run correctly like this (pseudo-commands):

conda install cudatoolkit=11.2 cudnn=8.1.0 python=3.8
export LD_LIBRARY_PATH=(conda path here)/lib                                           
                                                                                                 
# Activate conda base environment then:
python -m pip install --upgrade setuptools pip                                     
python -m pip install nvidia-pyindex                                               
python -m pip install nvidia-tensorrt==7.2.3.4                                     
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${verdir}/lib/python3.8/site-packages/tensorrt/          
python -m pip install tf-nightly                                                   
python -m pip install careless                                                           

After this all examples complete using GPU, with no errors or warnings except:

careless_little:   completes but cannot get it to use GPU
careless_zero:  fails with code error - will note in separate issue
pyp:   needs XLA_FLAGS set to location of cuda:
export XLA_FLAGS=--xla_gpu_cuda_data_dir=(path to )/cuda/11.2

Overall, issue is resolved for us, thanks.
