### ISSUE TITLE
dependencies version

### ISSUE THREAD

**Issue by DorisMai** [rs-station/careless#88]
I was trying the hewlssad example by running the following command:

```
careless mono \        
    --anomalous  \
    --disable-image-scales \
    --merge-half-datasets \
    --iterations=10 \
    "BATCH,dHKL,Hobs,Kobs,Lobs,XDET,YDET,BG,SIGBG,LP,QE,FRACTIONCALC" \
    unmerged.mtz \
    merge/normal/hewl
```

I had to fix the following dependency version issues, and I thought the authors might be interested to know and add some checks in the installation script.

1. Error with spicy-1.6.2 (too outdated): 

> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

, which shows up in careless/models/merging/surrogate_posteriors.py", line 81, in _scipy_moment_4
    mom4 = truncnorm.moment(4, a, b, loc, scale)

2. Error with numpy-1.24.2 (too new, fixed by downgrading to 1.21): 

> AttributeError: module 'numpy' has no attribute 'typeDict'

**Comment by kmdalton** [comment]
I'll have to look into this some more. Can you tell me some more details about how you installed `careless`? Were these versions of `numpy` and `scipy` already installed in your python interpreter prior to installing `careless`? I would recommend installing `careless` (and anything TensorFlow-based for that matter) in a fresh `conda` environment. TF has ultra-specific version requirements for `numpy` and `scipy` that aren't always handled well by `pip`. I should probably make a note of that in the README.

**Comment by kmdalton** [comment]
I could try to fix this by updating the `setup.py` for the `careless` repo. I hesitate to do that because `tf` is very picky about its dependency versioning. I have found in the past that being too specific with my requirements leads to endless dependency whack-a-mole. 

Instead, I edited the README to advise users to start with a fresh conda env (#89). That seems like a more durable solution to me.

**Comment by kmdalton** [comment]
@DorisMai, I think your errors are bypassed by using a fresh environment, right? I think it makes sense to stick with that as a recommendation. It is the official way to install TensorFlow as per the docs.

 I will close this issue if you do not mind. Let me know if I am missing anything here. Thanks!
