### ISSUE TITLE
update to python 3.11

### ISSUE THREAD

**Issue by kmdalton** [rs-station/careless#96]
The current install instructions on the front page ask users to install python 3.11, but `setup.py` prevents `careless` from installing on python 3.11.  To remedy, 

- [x]  update setup.py to allow 3.11
- [x]  add python 3.11 to the build matrix

**Comment by DHekstra** [comment]
fun fact--the instructions at https://www.tensorflow.org/install/pip#step-by-step_instructions still ask for Python 3.9.

**Comment by kmdalton** [comment]
gadzooks. well -- the careless tests pass on 3.11.  i hope i don't regret updating.
